name: Validate HACS
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Download repo
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Setup Python
        with:
          python-version: '3.13.x'

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands